# Generated by Django 2.2.7 on 2019-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='observers',
            field=models.ManyToManyField(related_name='observers', to='tracker.Habit'),
        ),
        migrations.DeleteModel(
            name='Observer',
        ),
    ]
