# Generated by Django 2.2.7 on 2019-11-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191106_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='habits',
            new_name='tracker',
        ),
    ]
