# Generated by Django 2.2.7 on 2019-11-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191106_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='records',
            new_name='habit',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='tracker.Habit'),
        ),
    ]
