# Generated by Django 2.2.7 on 2019-11-07 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20191106_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='observers',
            field=models.ManyToManyField(blank=True, null=True, related_name='observers', to='tracker.Habit'),
        ),
    ]
