# Generated by Django 2.2.7 on 2019-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20191107_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observers', to='tracker.Habit'),
        ),
    ]
