# Generated by Django 2.2.7 on 2019-11-09 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20191108_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='adjustment',
            field=models.CharField(default='=', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 30, 15, 35, 31, 115744, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='habit',
            name='freq',
            field=models.CharField(default='daily', max_length=10),
        ),
    ]
