# Generated by Django 2.2.7 on 2019-11-09 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20191109_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 30, 19, 59, 31, 72890, tzinfo=utc)),
        ),
    ]
